---
editor_options: 
  markdown: 
    wrap: 72
---

This folder contains code for analyzing cleaned data sets and aids in
visualization of parameters of interest.

\
(1) `dust` folder

-   `daily_dust.qmd`: looks at dust concentration over the daily time
    series.

-   `dust_and_copies.qmd:` combines Vibrio enumeration with dust data.

\
(2) The `environment` folder

-   `env_par.qmd`: examines environmental parameters of interest.

\
(3) The `qPCR` folder

-   `daily_qmd`: has data on Vibrio enumeration. This is also seen in
    the `dust_and_copies.qmd` in the dust subfolder

\
(4) The `stats` folder:

-   `1_distributiom.qmd`: Checks distribution of variables of interest

-   `2_cca.qmd`: Performs cross-correlation analysis to test for lags in
    time series (between dust input and Vibrio growth)

-   `3_correlation.qmd`: Runs Correlation matrices on all variables

-   `4_uni_variate.qmd` : runs univariate models on variable and
    predictors of interest.

-   `5_multi_variate_models folder`: Contains scripts that runs
    multivariate models on variable of interest (copies_mL) and random
    forest models.
