---
title: "Exploratory_monthly"
format:
  html:
    theme: default
---

Library
```{r}
library(tidyverse)
library(here)
```

Load Data
```{r}
copies<- read_csv(here("data", "processed_data", "total_clean_copies.csv")) #This is the clean_data.csv from copies_calculator but with date manually added in,
```

Make mini dataframes for each site
```{r}

#Monthly All sites
monthly<- copies %>%
  select(date,copies_mL,site,Type) %>%
  filter(Type %in% "Monthly") #Need to add July date here somehow


#Monthly by Site
bo_monthly <- monthly %>% filter(site %in% "BO") #Blind Oso Bay
c2_monthly <- monthly %>% filter(site %in% "C2") #Canals
rd_monthly <- monthly %>% filter(site %in% "RD") #Gulf Site


```

Total Monthly Vibrio at Gulf
```{r}
rd_monthly %>%
  ggplot() +geom_line(
    aes(x = date,
        y = copies_mL),
    color = "darkblue") +
  theme_bw() +
  labs(
    x = "Date",
    y = "Copies/mL",
    title = "Total Monthly Vibrio at Gulf Site") +
  theme(plot.title = element_text(hjust = 0.5))
```


Total Monthly Vibrio at Canals
```{r}
c2_monthly %>%
  ggplot() +geom_line(
    aes(x = date,
        y = copies_mL),
    color = "darkorange") +
  theme_bw() +
  labs(
    x = "Date",
    y = "Copies/mL",
    title = "Total Monthly Vibrio at Canals") +
  theme(plot.title = element_text(hjust = 0.5))
```

Total Monthly Vibrio at Blind Oso
```{r}
bo_monthly %>%
  ggplot() +geom_line(
    aes(x = date,
        y = copies_mL),
    color = "darkgreen") +
  theme_bw() +
  labs(
    x = "Date",
    y = "Copies/mL",
    title = "Total Monthly Vibrio at Blind Oso") +
  theme(plot.title = element_text(hjust = 0.5))
```

Total Monthly Vibrio
```{r}
tot_vib_allsites_monthly <- monthly %>%
  ggplot()+geom_line(
  aes(x = date,
      y = copies_mL,
      color = site))+
  geom_point(
    aes(x = date,
        y = copies_mL,
        color = site ))+
  facet_wrap(~site) +
  theme_bw()+
  labs(
    x = "Date",
    y = "Copies/mL",
    title = "Total Monthly Vibrio at all Sites",
    caption = "This includes 3 May events and does not include July") +
  theme(plot.title = element_text(hjust = 0.5)) + #center title
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) + #Tilt x axis labels 
  theme(legend.position = "none") #Removes legend 

tot_vib_allsites_monthly
```
Save as PNG
```{r}
png(file = here("results","plots", "tot_vib_allsites_monthly.png"))
tot_vib_allsites_monthly
dev.off()
```

