---
title: "Exploratory_monthly"
format:
  html:
    theme: default
---

Library
```{r}
library(tidyverse)
library(here)
library(lubridate)
```

Load Data
```{r}
copies<- read_csv(here("data", "processed_data", "total_clean_copies.csv")) #This is the clean_data.csv from copies_calculator but with date manually added in,
```

Make mini dataframes for each site
```{r}
copies<- copies %>%
  mutate(site= recode(site, "BO" = "Blind Oso",
                       "C2" = "Canals",
                       "RD" = "Gulf"))

#Monthly All sites: Includes 3 Sample events in May 
monthly_may<- copies %>%
  mutate(monthly = case_when(date == "2022-07-07" ~ "Monthly", #This adds a July date to be included in monthly analysis
                             Type == "Monthly" ~ "Monthly")) %>%
  select(date,copies_mL,site,monthly) %>%
  filter(monthly %in% "Monthly") 

#Monthly All sites: Includes ONE sample from May 
monthly<- monthly_may %>%
  filter(!date %in% as.Date(c("2022-05-20", "2022-05-24")))


#Monthly by Site
bo_monthly <- monthly %>% filter(site %in% "Blind Oso") #Blind Oso Bay
c2_monthly <- monthly %>% filter(site %in% "Canals") #Canals
rd_monthly <- monthly %>% filter(site %in% "Gulf") #Gulf Site


```

Total Monthly Vibrio at Gulf
```{r}
rd_monthly %>%
  ggplot() +geom_line(
    aes(x = date,
        y = copies_mL),
    color = "#4c848c",
    size = 1) +
  theme_bw() +
  labs(
    x = "Date",
    y = "Copies/mL",
    title = "Total Monthly Vibrio at Gulf Site") +
  theme(plot.title = element_text(hjust = 0.5))
```


Total Monthly Vibrio at Canals
```{r}
c2_monthly %>%
  ggplot() +geom_line(
    aes(x = date,
        y = copies_mL),
    color = "#ba4716",
    size = 1) +
  theme_bw() +
  labs(
    x = "Date",
    y = "Copies/mL",
    title = "Total Monthly Vibrio at Canals") +
  theme(plot.title = element_text(hjust = 0.5))
```

Total Monthly Vibrio at Blind Oso
```{r}
bo_monthly %>%
  ggplot() +geom_line(
    aes(x = date,
        y = copies_mL),
    color = "#809C52",
    size =1) +
  theme_bw() +
  labs(
    x = "Date",
    y = "Copies/mL",
    title = "Total Monthly Vibrio at Blind Oso") +
  theme(plot.title = element_text(hjust = 0.5))
```

Total Monthly Vibrio
```{r}
tot_vib_allsites_monthly <- monthly %>%
  ggplot()+geom_line(
  aes(x = date,
      y = copies_mL,
      color = site),
  size = 1)+
  facet_wrap(~site) +
  theme_bw()+
  labs(
    x = "Date",
    y = "Copies/mL",
    title = "Total Monthly Vibrio at all Sites") +
  theme(
    plot.title = element_text(hjust = 0.5, size = 15),  #center title
    axis.text.x = element_text(angle = 45, hjust = 1),
    axis.text.y = element_text(size = 10),
    legend.position = "none")+ #Removes legend 
scale_color_manual(values = c("Blind Oso" = "#809C52",
                              "Canals" = "#ba4716",
                              "Gulf" = "4c848c"))
tot_vib_allsites_monthly
```
Save as PNG
```{r}
png(file = here("results","plots", "tot_vib_allsites_monthly.png"))
tot_vib_allsites_monthly
dev.off()
```

