---
title: "Statistical analysis"
format:
  html:
    theme: default
---
Library
```{r}
library(tidyverse)
library(here)
```

Load Data that has COPIES and DUST CONC
```{r}
dust_sum<- readRDS(here("data", "processed_data", "dust_sum_copies.rds"))
dust_0 <- readRDS(here("data", "processed_data", "dust_0_copies.rds"))
dust_6 <- readRDS(here("data", "processed_data", "dust_6_copies.rds"))
dust_12 <- readRDS(here("data", "processed_data", "dust_12_copies.rds"))
dust_18 <- readRDS(here("data", "processed_data", "dust_18_copies.rds"))
```

Make df for Daily time series with dust sum 
```{r}
daily<- dust_sum %>%
filter(between(date, as.Date('2022-07-07'), as.Date('2022-07-19'))) #We do not have copies_mL for 2022-07-10
```

df with daily for t0-t18
```{r}
daily0<- dust_0 %>%
filter(between(date, as.Date('2022-07-07'), as.Date('2022-07-19'))) #We do not have copies_mL for 2022-07-10

daily6<- dust_6 %>%
filter(between(date, as.Date('2022-07-07'), as.Date('2022-07-19'))) #We do not have copies_mL for 2022-07-10

daily12<- dust_12 %>%
filter(between(date, as.Date('2022-07-07'), as.Date('2022-07-19'))) #We do not have copies_mL for 2022-07-10

daily18<- dust_18 %>%
filter(between(date, as.Date('2022-07-07'), as.Date('2022-07-19'))) #We do not have copies_mL for 2022-07-10
```



Running Stats
```{r}
tsum<- lm(dust~copies_mL, data = daily)
summary(tsum)

t0<- lm(dust~copies_mL, data = daily0)
summary(t0)

t6<- lm(dust~copies_mL, data = daily6)
summary(t6)

t12<- lm(dust~copies_mL, data = daily12)
summary(t12)
```





