---
title: "Vv explore"
format:
  html:
    theme: default
---

Libraries
```{r}
library(tidyverse)
library(here)
library(ggpubr)
```

Data
```{r}
vv<- read_csv(file = here("data", "processed_data", "vv_clean_copies.csv")) 
#sq <-read_csv(here("data", "raw_data", "vv_qPCR_daily_0.csv"))
redo<- read_csv(here("data", "processed_data", "vv_clean_copies_redo.csv"))
t3<-  read_csv(here("data", "processed_data", "vv_clean_copies_trial3.csv"))
```

Vv Standard Curve
```{r}
#std<- sq %>%
 # filter(Content %in% "Std",
        # Fluor %in% "HEX") #%>%
  #ggplot() + geom_point(
  #  aes(x = log(SQ),
      #  y = Cq))
#std
```


Make Site df
```{r}
rd6<- t3 %>%
  filter(site %in% "RD")

c2<- t3 %>%
  filter(site %in% "C2")

bo<- t3 %>%
  filter(site %in% "BO")
```

Plot Vv at C2
```{r}
c2_vv<- c2 %>% ggplot() + geom_line(
  aes(x = date,
      y = copies_mL),
  color = "darkred") +
  geom_point(
    aes(x = date,
      y = copies_mL),
  color = "darkred")+
  theme_bw() +
  labs(x = "Date",
       y = "Copies/mL",
       title = "Vv at Canals") +
  theme(plot.title = element_text(hjust = 0.5))


c2_vv
```

Plot Vv at RD
```{r}
rd_vv<- rd6 %>% ggplot() + geom_line(
  aes(x = date,
      y = copies_mL),
  color = "darkblue")+
  geom_point(
    aes(x = date,
      y = copies_mL),
  color = "darkblue")+
  theme_bw() +
  labs(x = "Date",
       y = "Copies/mL",
       title = "Vv at Gulf") +
  theme(plot.title = element_text(hjust = 0.5))


rd_vv
```

Plot Vv at BO
```{r}
bo_vv<- bo %>% ggplot() + geom_line(
  aes(x = date,
      y = copies_mL),
  color = "darkgreen")+
  geom_point(
    aes(x = date,
      y = copies_mL),
  color = "darkgreen")+
  theme_bw() +
  labs(x = "Date",
       y = "Copies/mL",
       title = "Vv at Blind Oso") +
  theme(plot.title = element_text(hjust = 0.5))


bo_vv
```
Stack
```{r}
figure<- ggarrange(c2_vv, bo_vv, rd_vv + font("x.text", size = 10),
                    ncol = 1, nrow = 3) #Final plot is 1 column and 2 rows 

                
figure
```

All sites Trial 1
```{r}
all<- vv %>% 
  mutate(site = recode(site, "BO" = "Blind Oso",
                              "C2" = "Canals",
                              "RD" = "Gulf")) %>%
  ggplot() + geom_line(
    aes(x = date,
        y = copies_mL,
        color = site)) + 
  scale_color_manual( values = c("Blind Oso" = "darkgreen",
                                "Canals" = "darkred",
                                "Gulf" = "darkblue"))+
  theme_bw()+
  facet_wrap(~site)+
  labs(
    x = "Date", 
    y = "Copies/mL",
    title = "Vibrio vulnificus Levels Across Dust Time Series: Trial 1")+
  theme(
    legend.position = "none",
    axis.text.x = element_text(angle = 45, hjust = 1),
    plot.title = element_text(hjust = 0.5),
    axis.text.y = element_text(size = 15)) 
  
all
```

All Site Trial 2
```{r}
all_redo<- redo %>% 
  mutate(site = recode(site, "BO" = "Blind Oso",
                              "C2" = "Canals",
                              "RD" = "Gulf")) %>%
  ggplot() + geom_line(
    aes(x = date,
        y = copies_mL,
        color = site)) + 
  scale_color_manual( values = c("Blind Oso" = "darkgreen",
                                "Canals" = "darkred",
                                "Gulf" = "darkblue"))+
  theme_bw()+
  facet_wrap(~site)+
  labs(
    x = "Date", 
    y = "Copies/mL",
    title = "Vibrio vulnificus Levels Across Dust Time Series: Trial 2")+
  theme(
    legend.position = "none",
    axis.text.x = element_text(angle = 45, hjust = 1),
    plot.title = element_text(hjust = 0.5),
    axis.text.y = element_text(size = 15)) 
  
all_redo
```

All Sites Trial 3
```{r}
all_t3<- t3 %>% 
  mutate(site = recode(site, "BO" = "Blind Oso",
                              "C2" = "Canals",
                              "RD" = "Gulf")) %>%
  ggplot() + geom_line(
    aes(x = date,
        y = copies_mL,
        color = site)) + 
  scale_color_manual( values = c("Blind Oso" = "darkgreen",
                                "Canals" = "darkred",
                                "Gulf" = "darkblue"))+
  theme_bw()+
  facet_wrap(~site)+
  labs(
    x = "Date", 
    y = "Copies/mL",
    title = "Vibrio vulnificus Levels Across Dust Time Series: Trial 3")+
  theme(
    legend.position = "none",
    axis.text.x = element_text(angle = 45, hjust = 1),
    plot.title = element_text(hjust = 0.5),
    axis.text.y = element_text(size = 15)) 
  
all_t3
```


Compare Trial 1 and 2
```{r, fig.height=7, fig.width=7}
figure2<- ggarrange(all, all_redo, all_t3,
                    ncol = 1, nrow = 3)
figure2
```

Save Vv at all sites as PNG
```{r}
png(file = here("results", "plots", "vv_all_sites.png")) #Saving c2
all
dev.off()

png(file = here("results", "plots", "vv_all_sites_redo.png")) #Saving c2
all_redo
dev.off()

```
