---
title: "Copies/mL"
format:
  html:
    theme: default
---
Libraries
```{r}
library(tidyverse)
library(here)
```

Load data
```{r}
data <-read_csv(here("data", "raw_data", "copies_master.csv"))
```

Select and Filter for Daily and Monthly Time Series 
```{r}
daily1<- data %>%
select(Type,Sample, Cq,filter_amt, dilution) %>%
  filter(Type %in% "Daily")

monthly1<- data %>%
select(Type,Sample, Cq,filter_amt, dilution) %>%
  filter(Type %in% "Monthly")
```

Go from CQ --> Copies/mL
```{r}
daily2<- daily1 %>%
    mutate(
    log_sq = ((Cq-36.114)/-3.3844), #Equation of the line to get log(SQ)
    sq = 10^log_sq, #Unlog 
    copies_rxn = sq*10, #SQ*Reaction Volume
    copies_uL_1_10 = copies_rxn/2.5, #Copies/RXN / DNA Template Volume
    copies_uL_extract = copies_uL_1_10 *dilution, #(Copies/uL of 1:10)*(1 if there was no sample dilution // *10 if there was a 1:10 dilution etc.)
    concentration_factor = 100/filter_amt, #(Concentration factor = amount of eluted DNA from ZYMO) / (filter amount from vacuum filtration)
    copies_mL = copies_uL_extract*concentration_factor) %>%
    
  select(Sample,copies_mL,Type)

monthly2<- monthly1 %>%
    mutate(
    log_sq = ((Cq-36.114)/-3.3844), #Equation of the line to get log(SQ)
    sq = 10^log_sq, #Unlog 
    copies_rxn = sq*10, #SQ*Reaction Volume
    copies_uL_1_10 = copies_rxn/2.5, #Copies/RXN / DNA Template Volume
    copies_uL_extract = copies_uL_1_10 *dilution, #(Copies/uL of 1:10)*(1 if there was no sample dilution // *10 if there was a 1:10 dilution etc.)
    concentration_factor = 100/filter_amt, #(Concentration factor = amount of eluted DNA from ZYMO) / (filter amount from vacuum filtration)
    copies_mL = copies_uL_extract*concentration_factor) %>%
    
  select(Sample,copies_mL,Type)

```


Create Site Column from Sample Name 
```{r}
daily3<- daily2 %>%
  mutate(site = substr(daily2$Sample,1,2)) #Creates new column `Site` from the first two letters in `Sample` (BO16 becomes BO)

monthly3<- monthly2 %>%
  mutate(site = substr(monthly2$Sample,1,2)) #Creates new column `Site` from the first two letters in `Sample` (BO16 becomes BO)
```



Take the average of qPCR triplicates 
```{r}
daily_final<- daily3 %>% group_by(Sample,site,Type) %>% #Group all chr together. All that should be left out is the numeric vector we want to work with (in this case, copies_mL)
  summarize_if(is.numeric, mean) %>%
  ungroup() #Ungroup to spit everything back out


monthly_final<- monthly3 %>% group_by(Sample,site,Type) %>% #Group all chr together. All that should be left out is the numeric vector we want to work with (in this case, copies_mL)
  summarize_if(is.numeric, mean) %>%
  ungroup() #Ungroup to spit everything back out
```


```{r}
copies_final<- full_join(monthly_final,daily_final)
```


Save as RDS and CSV
```{r}
saveRDS(copies_final, file= here("data","processed_data","clean_data.rds"))
write.csv(copies_final,file= here("data","processed_data","clean_data.csv")) 

```

