---
title: "Vv caluclator"
format:
  html:
    theme: default
---
*This dataset is Daily Vv qPCR*

Libraries
```{r}
library(tidyverse)
library(here)
```

Load data
```{r}
sq <-read_csv(here("data", "raw_data", "vv_run_daily_TX_dust_2_7_23 -  Quantification Summary.csv")) #Manually replaced NaN with 0 for no amplifcation, added filter_amt and dilution
redo<- read_csv(here("data", "raw_data", "vv_run_daily_TX_dust_2_9_23 -  Quantification Summary.csv")) #Manually replaced NaN with 0 for no amplifcation, added filter_amt and dilution
```

Filter for HEX dye (samples). Cy5 is for IAC
```{r}
sq2<- sq %>% 
  select(filter_amt,SQ,Cq, Sample, Fluor, dilution) %>%
  filter(Fluor %in% "HEX")

redo2<- redo %>% 
  select(filter_amt,Cq, Sample, Fluor, dilution, Well) %>%
  filter(Fluor %in% "HEX",
         !Well %in% "K19")

SQ_test<- sq %>% 
  select(filter_amt,SQ,Cq, Sample, Fluor, dilution) %>%
  filter(Fluor %in% "HEX")


```

Cq --> Copies/mL
```{r}
copies<- sq2 %>%
   mutate(
   log_sq = ((Cq-36.497)/-3.166), #Equation of the line to get log(SQ)
    sq = 10^log_sq, #Unlog 
    copies_rxn = sq*15, #SQ*Reaction Volume
    copies_uL_1_10 = copies_rxn/1.2, #Copies/RXN / DNA Template Volume
    copies_uL_extract = copies_uL_1_10 *dilution, #(Copies/uL of 1:10)*(1 if there was no sample dilution // *10 if there was a 1:10 dilution etc.)
    concentration_factor = 100/filter_amt, #(Concentration factor = amount of eluted DNA from ZYMO) / (filter amount from vacuum filtration)
    copies_mL = copies_uL_extract*concentration_factor) %>%
    
select(Sample,copies_mL)

copies_redo<- redo2 %>%
    mutate(
    log_sq = ((Cq-36.497)/-3.166), #Equation of the line to get log(SQ)
    sq = 10^log_sq, #Unlog 
    copies_rxn = sq*15, #SQ*Reaction Volume
    copies_uL_1_10 = copies_rxn/1.2, #Copies/RXN / DNA Template Volume
    copies_uL_extract = copies_uL_1_10 *dilution, #(Copies/uL of 1:10)*(1 if there was no sample dilution // *10 if there was a 1:10 dilution etc.)
    concentration_factor = 100/filter_amt, #(Concentration factor = amount of eluted DNA from ZYMO) / (filter amount from vacuum filtration)
    copies_mL = copies_uL_extract*concentration_factor) %>%
    
select(Sample,copies_mL)

SQ_test1<- sq %>%
    mutate(
   # log_sq = ((Cq-36.497)/-3.166), #Equation of the line to get log(SQ)
   # sq = 10^log_sq, #Unlog 
    copies_rxn = SQ*15, #SQ*Reaction Volume
    copies_uL_1_10 = copies_rxn/1.2, #Copies/RXN / DNA Template Volume
    copies_uL_extract = copies_uL_1_10 *dilution, #(Copies/uL of 1:10)*(1 if there was no sample dilution // *10 if there was a 1:10 dilution etc.)
    concentration_factor = 100/filter_amt, #(Concentration factor = amount of eluted DNA from ZYMO) / (filter amount from vacuum filtration)
    copies_mL = copies_uL_extract*concentration_factor) %>%
    
select(Sample,copies_mL)
```

Create Site Column from Sample Name 
```{r}
copies2<- copies %>%
  mutate(site = substr(copies$Sample,1,2)) #Creates new column `Site` from the first two letters in `Sample` (BO16 becomes BO)

copies2_redo<- copies_redo %>%
  mutate(site = substr(copies_redo$Sample,1,2)) #Creates new column `Site` from the first two letters in `Sample` (BO16 becomes BO)

```

Replace NaN with 0 for copies/mL
```{r}
copies3<- copies2 %>% 
 mutate(copies_mL = ifelse(is.na(copies_mL), 0, copies_mL)) %>%
filter(!is.na(Sample))  #Dropping NAs from STD Curve


copies3_redo<- copies2_redo %>%
 mutate(copies_mL = ifelse(is.na(copies_mL), 0, copies_mL)) %>%
filter(!is.na(Sample))  #Dropping NAs from STD Curve
```

Take the average of qPCR triplicates 
```{r}
copies4<- copies3 %>% 
  group_by(site, Sample) %>% #Group all chr together. All that should be left out is the numeric vector we want to work with (in this case, copies_mL)
  summarize_if(is.numeric, mean) %>%
  ungroup() #Ungroup to spit everything back out 
  
copies4_redo<- copies3_redo %>% 
  group_by(site, Sample) %>% #Group all chr together. All that should be left out is the numeric vector we want to work with (in this case, copies_mL)
  summarize_if(is.numeric, mean) %>%
  ungroup() #Ungroup to spit everything back out 
```

Save as RDS and manually add date in excel
```{r}
write.csv(copies4, file= here("data","processed_data","vv_clean_copies.csv"))
write.csv(copies4_redo, file= here("data","processed_data","vv_clean_copies_redo.csv"))
```






